package:
  name: QQQ
  displayName: '111'
  version: 1.0.0
  description: '111'
  category: å†²åŽ‹
  tags:
  - Mä»£ç 
  author: '111'
  icon: ðŸ“¦
  color: '#3498db'
  language: zh-CN
dependencies: []
templates:
  main: templates/main.j2
variables:
  groups:
    basic:
      name: åŸºæœ¬å‚æ•°
      icon: ðŸ”§
      parameters:
        program_name:
          type: string
          label: ç¨‹åºåç§°
          description: æ•°æŽ§ç¨‹åºçš„åç§°
          default: QQQ
          required: true
        program_number:
          type: number
          label: ç¨‹åºå·
          description: Oç¨‹åºå·
          default: 10001
          required: true
        tool_number:
          type: number
          label: åˆ€å…·å·
          description: åˆ€å…·ç¼–å·
          default: 1
          required: true
        spindle_speed:
          type: speed
          label: ä¸»è½´è½¬é€Ÿ
          unit: rpm
          default: 3000
          range:
          - 100
          - 30000
          required: true
        feed_rate:
          type: speed
          label: è¿›ç»™é€Ÿåº¦
          unit: mm/min
          default: 1500
          range:
          - 10
          - 10000
          required: true
        start_x:
          type: length
          label: èµ·å§‹Xåæ ‡
          unit: mm
          default: 0
          required: true
        start_y:
          type: length
          label: èµ·å§‹Yåæ ‡
          unit: mm
          default: 0
          required: true
        safe_height:
          type: length
          label: å®‰å…¨é«˜åº¦
          unit: mm
          default: 10
          range:
          - 1
          - 100
          required: true
        tool_length:
          type: length
          label: åˆ€å…·é•¿åº¦
          unit: mm
          default: 50
          required: true
        description:
          type: string
          label: ç¨‹åºæè¿°
          description: ç¨‹åºè¯´æ˜Žä¿¡æ¯
          default: ''
          required: false
        creation_date:
          type: string
          label: åˆ›å»ºæ—¥æœŸ
          description: ç¨‹åºåˆ›å»ºæ—¥æœŸ
          default: '2026-01-15'
          required: false
        rapid_moves:
          type: array
          label: å¿«é€Ÿç§»åŠ¨ç‚¹
          description: å¿«é€Ÿç§»åŠ¨åæ ‡ç‚¹åˆ—è¡¨
          default: []
          required: false
outputs:
  default_format: .nc
  supported_formats:
  - .nc
  - .mpf
  - .spf
  - .txt
  files:
    main_program:
      template: templates/main.j2
      filename_pattern: '{{program_name}}'
      extension: .nc
      description: ä¸»åŠ å·¥ç¨‹åº
      enabled: true
      is_default: true
presets:
  é»˜è®¤:
    description: é»˜è®¤å‚æ•°
    parameters: {}
validation:
  rules:
    safe_height_check:
      condition: safe_height > 5
      message: å®‰å…¨é«˜åº¦å»ºè®®å¤§äºŽ5mm
      level: warning
